# Playground Page Configuration
# This file defines the playground page for testing and developing components

page:
  title: "Playground"
  route: "/playground"
  description: "Component testing and development playground"

layout:
  type: "grid"
  columns: 8
  gap: 2
  padding: 3
  grouping:
    enabled: true
    selector:
      position:
        col: 1
        row: 1
        span: 8
      multiSelect: true
      defaultGroups: ["headers", "navigation", "data", "interactive"]

# Theme configuration removed - using dynamic database themes instead

componentGroups:
  headers:
    name: "Headers & Welcome"
    description: "Page headers and welcome components"
    color: "#3B82F6"
  navigation:
    name: "Navigation & Links"
    description: "Navigation cards and link components"
    color: "#10B981"
  data:
    name: "Data Display"
    description: "Charts, metrics, and data visualization"
    color: "#8B5CF6"
  interactive:
    name: "Interactive Components"
    description: "Chat, forms, and interactive widgets"
    color: "#F59E0B"

components:
  # Group Selector Component
  - id: "group-selector"
    type: "GroupSelector"
    position:
      col: 1
      row: 1
      span: 8
    props:
      groups: ["headers", "navigation", "data", "interactive"]
      defaultSelected: ["headers", "navigation", "data", "interactive"]

  # Headers & Welcome Components
  - id: "welcome-header"
    type: "WelcomeHeader"
    group: "headers"
    position:
      col: 1
      row: 2
      span: 8
    props:
      title: "Playground"
      subtitle: "Component Testing & Development"
      
  # Navigation & Link Cards
  - id: "database-link-card"
    type: "DatabaseLinkCard"
    group: "navigation"
    position:
      col: 1
      row: 3
      span: 2
    props:
      title: "Databases"
      description: "Manage your databases"
      href: "/databases"
      icon: "Database"
      
  - id: "tasks-link-card"
    type: "TasksLinkCard"
    group: "navigation"
    position:
      col: 3
      row: 3
      span: 2
    props:
      title: "Task Management"
      description: "Organize and track tasks"
      href: "/tasks"
      icon: "CheckSquare"

  - id: "quick-start-card"
    type: "QuickStartCard"
    group: "navigation"
    position:
      col: 5
      row: 3
      span: 2
    props:
      title: "Quick Start"
      description: "Get started quickly"
      primaryAction:
        text: "Get Started"
        href: "/quickstart"

  # Data Display Components
  - id: "kpi-cards"
    type: "KPICards"
    group: "data"
    position:
      col: 1
      row: 4
      span: 8
    props:
      metrics:
        - id: "total-revenue"
          title: "Total Revenue"
          value: 0
          suffix: ""
          description: "From orders table"

  # Interactive Components
  - id: "chatbot"
    type: "ChatBot"
    group: "interactive"
    position:
      col: 1
      row: 5
      span: 4
    props:
      className: "playground-chatbot"

  - id: "issue-tracker"
    type: "IssueTracker"
    group: "interactive"
    position:
      col: 5
      row: 5
      span: 4
    props:
      pageId: "playground"
      className: "playground-issue-tracker"

data:
  sources:
    - name: "orders"
      type: "supabase"
      query: "SELECT COUNT(*) as count, SUM(amount) as revenue FROM orders"
      refresh: "30s"
    - name: "customers"
      type: "supabase"  
      query: "SELECT COUNT(*) as count FROM customers"
      refresh: "1m"

navigation:
  showSidebar: true
  customHeader: false
  breadcrumbs: true

meta:
  author: "Playground Development Team"
  version: "1.0.0"
  lastModified: "2025-07-02"
  tags: ["playground", "testing", "development", "components"]