# Playground Page Configuration
# This file defines the playground page for testing and developing components

page:
  title: "Playground"
  route: "/playground"
  description: "Component testing and development playground"

layout:
  type: "grid"
  columns: 8
  gap: 2
  padding: 3
  grouping:
    enabled: true
    selector:
      position:
        col: 1
        row: 1
        span: 8
      multiSelect: true
      defaultGroups: ["headers", "navigation", "data", "interactive", "milestones"]

# Theme configuration removed - using dynamic database themes instead

componentGroups:
  headers:
    name: "Headers & Welcome"
    description: "Page headers and welcome components"
    color: "#3B82F6"
  navigation:
    name: "Navigation & Links"
    description: "Navigation cards and link components"
    color: "#10B981"
  data:
    name: "Data Display"
    description: "Charts, metrics, and data visualization"
    color: "#8B5CF6"
  interactive:
    name: "Interactive Components"
    description: "Chat, forms, and interactive widgets"
    color: "#F59E0B"
  milestones:
    name: "Milestone Management"
    description: "Milestone tracking and project management"
    color: "#EF4444"

components:
  # Group Selector Component
  - id: "group-selector"
    type: "GroupSelector"
    position:
      col: 1
      row: 1
      span: 8
    props:
      groups: ["headers", "navigation", "data", "interactive", "milestones"]
      defaultSelected: ["headers", "navigation", "data", "interactive", "milestones"]

  # Headers & Welcome Components
  - id: "welcome-header"
    type: "WelcomeHeader"
    group: "headers"
    position:
      col: 1
      row: 2
      span: 8
    props:
      title: "Playground"
      subtitle: "Component Testing & Development"
      
  # Navigation & Link Cards
  - id: "database-link-card"
    type: "DatabaseLinkCard"
    group: "navigation"
    position:
      col: 1
      row: 3
      span: 2
    props:
      title: "Databases"
      description: "Manage your databases"
      href: "/databases"
      icon: "Database"
      
  - id: "tasks-link-card"
    type: "TasksLinkCard"
    group: "navigation"
    position:
      col: 3
      row: 3
      span: 2
    props:
      title: "Task Management"
      description: "Organize and track tasks"
      href: "/tasks"
      icon: "CheckSquare"

  - id: "quick-start-card"
    type: "QuickStartCard"
    group: "navigation"
    position:
      col: 5
      row: 3
      span: 2
    props:
      title: "Quick Start"
      description: "Get started quickly"
      primaryAction:
        text: "Get Started"
        href: "/quickstart"

  # Data Display Components
  - id: "kpi-cards"
    type: "KPICards"
    group: "data"
    position:
      col: 1
      row: 4
      span: 8
    props:
      metrics:
        - id: "total-revenue"
          title: "Total Revenue"
          value: 0
          suffix: ""
          description: "From orders table"

  # Interactive Components
  - id: "chatbot"
    type: "ChatBot"
    group: "interactive"
    position:
      col: 1
      row: 5
      span: 4
    props:
      className: "playground-chatbot"

  - id: "issue-tracker"
    type: "IssueTracker"
    group: "interactive"
    position:
      col: 5
      row: 5
      span: 4
    props:
      pageId: "playground"
      className: "playground-issue-tracker"

  # Milestone Management Components
  - id: "milestone-board"
    type: "MilestoneBoard"
    group: "milestones"
    position:
      col: 1
      row: 6
      span: 8
    props:
      projectId: "project-1"

  - id: "milestone-progress-tracker"
    type: "MilestoneProgressTracker"
    group: "milestones"
    position:
      col: 1
      row: 7
      span: 4
    props:
      milestoneId: "milestone-1"

  - id: "milestone-dependency-manager"
    type: "MilestoneDependencyManager"
    group: "milestones"
    position:
      col: 5
      row: 7
      span: 4
    props:
      projectId: "project-1"

  # New Milestone Components
  - id: "milestone-card"
    type: "MilestoneCard"
    group: "milestones"
    position:
      col: 1
      row: 8
      span: 4
    props:
      milestone:
        id: "milestone-demo"
        projectId: "project-1"
        title: "Demo Milestone"
        description: "Example milestone for testing"
        status: "in_progress"
        priority: "high"
        color: "#3b82f6"
        progress: 65
        dueDate: "2025-08-15T23:59:59Z"
        createdAt: "2025-07-01T10:00:00Z"
        updatedAt: "2025-07-04T14:30:00Z"
        createdBy: "user-1"
        assignedTo: ["user-1", "user-2"]
        metadata:
          tags: ["demo", "testing"]
          estimatedHours: 120
          actualHours: 80
        isArchived: false
        dependencies: []
        tasks: []
      onEdit: "console.log"
      onDelete: "console.log"
      onStatusChange: "console.log"
      onProgressUpdate: "console.log"

  - id: "milestone-create-modal"
    type: "MilestoneCreateModal"
    group: "milestones"
    position:
      col: 5
      row: 8
      span: 4
    props:
      isOpen: false
      projects:
        - id: "project-1"
          name: "Website Redesign"
          description: "Complete overhaul of company website"
          color: "#3b82f6"
          ownerId: "user-1"
          createdAt: "2025-01-01T00:00:00Z"
          updatedAt: "2025-07-04T00:00:00Z"
          isArchived: false
          isFavorite: false
          teamMembers: ["user-1", "user-2", "user-3"]
          settings:
            allowComments: true
            allowAttachments: true
            requireDueDates: false
            customStatuses: []
          stats:
            totalTasks: 0
            completedTasks: 0
            overdueTasks: 0
            activeTasks: 0
            completionRate: 0
          milestones: []
          milestoneCount: 0
          completedMilestones: 0
          overdueMilestones: 0
          activeMilestones: 0
          milestoneCompletionRate: 0
      teamMembers:
        - id: "user-1"
          name: "John Doe"
          email: "john@example.com"
          role: "admin"
          isActive: true
          joinedAt: "2025-01-01T00:00:00Z"
        - id: "user-2"
          name: "Jane Smith"
          email: "jane@example.com"
          role: "member"
          isActive: true
          joinedAt: "2025-01-01T00:00:00Z"
      existingMilestones: []
      onClose: "console.log"
      onSubmit: "console.log"

  - id: "task-milestone-selector"
    type: "TaskMilestoneSelector"
    group: "milestones"
    position:
      col: 1
      row: 9
      span: 4
    props:
      projectId: "project-1"
      milestones:
        - id: "milestone-1"
          projectId: "project-1"
          title: "MVP Release"
          description: "Launch minimum viable product"
          status: "in_progress"
          priority: "high"
          color: "#3b82f6"
          progress: 45
          dueDate: "2025-08-01T23:59:59Z"
          createdAt: "2025-06-01T10:00:00Z"
          updatedAt: "2025-06-30T14:30:00Z"
          createdBy: "user-1"
          assignedTo: ["user-1", "user-2"]
          metadata:
            tags: ["release", "mvp"]
          isArchived: false
          dependencies: []
          tasks: []
        - id: "milestone-2"
          projectId: "project-1"
          title: "Beta Testing"
          description: "Complete beta testing phase"
          status: "pending"
          priority: "high"
          color: "#10b981"
          progress: 0
          dueDate: "2025-09-15T23:59:59Z"
          createdAt: "2025-06-01T10:00:00Z"
          updatedAt: "2025-06-15T09:20:00Z"
          createdBy: "user-1"
          assignedTo: ["user-2"]
          metadata:
            tags: ["testing", "qa"]
          isArchived: false
          dependencies: []
          tasks: []
      onMilestoneSelect: "console.log"
      enableCreate: true
      onMilestoneCreate: "console.log"

  - id: "milestone-task-list"
    type: "MilestoneTaskList"
    group: "milestones"
    position:
      col: 5
      row: 9
      span: 4
    props:
      milestone:
        id: "milestone-1"
        projectId: "project-1"
        title: "MVP Release"
        description: "Launch minimum viable product"
        status: "in_progress"
        priority: "high"
        color: "#3b82f6"
        progress: 45
        dueDate: "2025-08-01T23:59:59Z"
        createdAt: "2025-06-01T10:00:00Z"
        updatedAt: "2025-06-30T14:30:00Z"
        createdBy: "user-1"
        assignedTo: ["user-1", "user-2"]
        metadata:
          tags: ["release", "mvp"]
        isArchived: false
        dependencies: []
        tasks: []
      tasks:
        - id: "task-1"
          title: "Design user interface"
          description: "Create mockups and prototypes"
          status:
            id: "in_progress"
            name: "In Progress"
            isCompleted: false
          priority: "high"
          dueDate: "2025-07-15T17:00:00Z"
          assigneeId: "user-1"
          tags: ["design", "ui"]
          createdAt: "2025-06-01T10:00:00Z"
          updatedAt: "2025-07-04T14:30:00Z"
          milestoneId: "milestone-1"
        - id: "task-2"
          title: "Implement authentication"
          description: "User login and registration"
          status:
            id: "completed"
            name: "Completed"
            isCompleted: true
          priority: "high"
          dueDate: "2025-07-10T17:00:00Z"
          assigneeId: "user-2"
          tags: ["backend", "auth"]
          createdAt: "2025-06-01T10:00:00Z"
          updatedAt: "2025-07-02T16:45:00Z"
          milestoneId: "milestone-1"
      teamMembers:
        - id: "user-1"
          name: "John Doe"
          avatarUrl: "https://via.placeholder.com/32"
        - id: "user-2"
          name: "Jane Smith"
          avatarUrl: "https://via.placeholder.com/32"
      onTaskCreate: "console.log"
      onTaskUpdate: "console.log"
      onTaskDelete: "console.log"
      onTaskUnlink: "console.log"

data:
  sources:
    - name: "orders"
      type: "supabase"
      query: "SELECT COUNT(*) as count, SUM(amount) as revenue FROM orders"
      refresh: "30s"
    - name: "customers"
      type: "supabase"  
      query: "SELECT COUNT(*) as count FROM customers"
      refresh: "1m"

navigation:
  showSidebar: true
  customHeader: false
  breadcrumbs: true

meta:
  author: "Playground Development Team"
  version: "1.0.0"
  lastModified: "2025-07-02"
  tags: ["playground", "testing", "development", "components"]